# Site Info
title:              "The Professional Semiprofessional Blog"
description:        "projects, updates (occasionally), other prof. development stuff."
author_name:        "Ateanna Uriri" # change this to your name
logo_url:           https://pbs.twimg.com/profile_images/1212194749815361536/30s5NrXe_400x400.jpg # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://aouriri.github.io # main url
baseurl:            /blog
permalink:          /:title # Post permalink
timezone:           America/Chicago # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jemoji



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
